services:
  postgres:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: cabeleleilaleiladb
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: cabeleleilaleila
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - cabeleleila-network


volumes:
  pgdata:

networks:
  cabeleleila-network:
    driver: bridge